
version: '3.8'

services:
  my_library:
    build: .
    container_name: my_library
    volumes:
      - .:/workspace
    # Permite interactuar con la terminal del contenedor
    stdin_open: true 
    tty: true
    working_dir: /workspace
    # Mantener el contenedor ejecutándose
    command: tail -f /dev/null